// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYQArAjLf2-SA6NuuilQcw954onA3_wk',
    appId: '1:626296179146:android:f5e2246cee5b5802b8e733',
    messagingSenderId: '626296179146',
    projectId: 'hiremate-4fe98',
    storageBucket: 'hiremate-4fe98.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT7aelbHFINToBjdcsKz5U208y1ND44O8',
    appId: '1:626296179146:web:11028ea9ed1ab765b8e733',
    messagingSenderId: '626296179146',
    projectId: 'hiremate-4fe98',
    authDomain: 'hiremate-4fe98.firebaseapp.com',
    storageBucket: 'hiremate-4fe98.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT7aelbHFINToBjdcsKz5U208y1ND44O8',
    appId: '1:626296179146:web:11028ea9ed1ab765b8e733',
    messagingSenderId: '626296179146',
    projectId: 'hiremate-4fe98',
    authDomain: 'hiremate-4fe98.firebaseapp.com',
    storageBucket: 'hiremate-4fe98.firebasestorage.app',
  );

}